version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint Workspace
          command: yarn lint
      - run:
          name: Test Workspace
          command: yarn test
      - run:
          name: Build Crisp
          command: yarn build
      - run:
          name: Browser Test
          command: yarn browser